# Generated by Django 4.1.6 on 2023-02-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("BoardRollNo", models.CharField(max_length=50)),
                ("RegistrationNo", models.CharField(max_length=50)),
                ("InstituteRoll", models.CharField(max_length=50)),
                ("Technology", models.CharField(max_length=50)),
                ("Shift", models.CharField(max_length=50)),
                ("Group", models.CharField(max_length=50)),
                ("Session", models.CharField(max_length=50)),
                ("FathersName", models.CharField(max_length=50)),
                ("MothersName", models.CharField(max_length=50)),
                ("Village", models.CharField(max_length=50)),
                ("PostOffice", models.CharField(max_length=50)),
                ("UpaZila", models.CharField(max_length=50)),
                ("District", models.CharField(max_length=50)),
                ("MobileNo", models.CharField(max_length=50)),
            ],
        ),
    ]
